# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86fa8d9359aaa636922ca7c84acb15d7154917a3c5b900e64d77d5d56d85ac851bfea8634c33f84cfe7be5da439a1e0fbf9451351477bd561b16434dc17319fb

test:
  secret_key_base: 97abb106c8da0517aa292dddf765258a457c322c4c2e55571d0e77631c3ba0fc8665e0034ba73a5d2bcd0f22cda4b8e56361b0757ac0a5e49c199cb33ef3e904

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
